### ISSUE TITLE
Plugin release and verification

### ISSUE THREAD

**Issue by fullkomnun** [ConsenSys/quorum-account-plugin-hashicorp-vault#10]
Hi,

I know this specific plugin and the Quorum accounts plugin architecture are currently in alpha state
but i'm interested in the approach. 
I cloned and built it for [playing purposes](https://github.com/fullkomnun/quorum-plugins-playground).
Is this plugin deployed to any publicly accessible plugin repository that can be referenced in [config](https://docs.goquorum.consensys.net/en/latest/HowTo/Configure/Plugins/#plugincentralconfiguration)?
Otherwise, assuming that the alternatives are locally building the plugin or deploying it to a private remote plugins repo,
what would be the best practices in terms of plugin [verification](https://docs.goquorum.consensys.net/en/latest/HowTo/Configure/Plugins/#plugincentralconfiguration)?

**Comment by chris-j-h** [comment]
Hi @fullkomnun 

There is a default plugin repository used by Quorum - https://dl.bintray.com/quorumengineering/quorum-plugins.  This includes release binaries for all plugins, as well as signatures and the public key for verification.  

This plugin central server requires no explicit configuration to use - if you provide no `PluginCentralConfiguration` then Quorum will download the plugin binary from this server at runtime if the binary does not already exist in the `baseDir`.  This means that you do not have to manually clone and build the plugin yourself.

If you want to use the latest master or a specific commit then this will require cloning and building yourself.

Integrity verification of the plugin binary is then peformed:

1. Quorum calculates the hash of the plugin binary
2. Quorum downloads the signature and public key from the plugin central server
3. Quorum uses the signature and public key to verify the binary being used is valid and has not been altered

In terms of alternatives to this default plugin central server you have two options:

1. **Custom plugin central server**

   Ensure the plugin binary and signed hash are uploaded to your plugin central server at path `/<plugin-name>/<version>/<arch>/` (basically mimic the directory structure of the default central server) and set `baseURL` and `publicKeyURI` in `PluginCentralConfiguration`

2. **Locally verify the plugin**

   Ensure the pluigin binary and signed hash are present in your  `baseDir` and provide the `--plugins.localverify` and `--plugins.publickey <path>` flags when starting your node.  Quorum will validate the binary without having to download anything from a plugin central server.
